Update BankAccountTest.java
Hi, the tests for this exercise are failing as 'assertEquals(double, double)' is deprecated 

Error message shown in the testing panel when reviewing tests on the failed submission:
Message: Use assertEquals(expected, actual, delta) to compare floating-point numbers
Exception: java.lang.AssertionError: Use assertEquals(expected, actual, delta) to compare floating-point numbers
	at BankAccountTest.canDepositMoneySequentially(BankAccountTest.java:39)